# Generated by Django 5.1.4 on 2024-12-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parachute',
            fields=[
                ('parachute_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('harness', models.CharField(blank=True, max_length=80, null=True)),
                ('main_canopy', models.CharField(blank=True, max_length=80, null=True)),
                ('reserve_canopy', models.CharField(blank=True, max_length=80, null=True)),
                ('aad', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'parachute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('jump_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('jump_number', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('parachute', models.CharField(blank=True, max_length=100, null=True)),
                ('parachute_0', models.ForeignKey(blank=True, db_column='parachute_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savejump.parachute')),
            ],
            options={
                'db_table': 'jump',
                'managed': True,
            },
        ),
    ]
