# Generated by Django 5.1.4 on 2024-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savejump', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Altitude',
            fields=[
                ('altitude_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('altitude', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'altitude',
                'managed': True,
            },
        ),
    ]
