# Generated by Django 5.1.4 on 2024-12-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savejump', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id_aircraft', models.SmallAutoField(primary_key=True, serialize=False)),
                ('aircraft', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'aircraft',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JumpType',
            fields=[
                ('id_jump_type', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jump_type',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='altitude',
            old_name='altitude_id',
            new_name='id_altitude',
        ),
        migrations.RenameField(
            model_name='jump',
            old_name='jump_id',
            new_name='id_jump',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_id',
            new_name='id_location',
        ),
        migrations.RenameField(
            model_name='parachute',
            old_name='parachute_id',
            new_name='id_parachute',
        ),
        migrations.RemoveField(
            model_name='jump',
            name='parachute_0',
        ),
        migrations.RemoveField(
            model_name='parachute',
            name='aad',
        ),
        migrations.RemoveField(
            model_name='parachute',
            name='harness',
        ),
        migrations.RemoveField(
            model_name='parachute',
            name='main_canopy',
        ),
        migrations.RemoveField(
            model_name='parachute',
            name='reserve_canopy',
        ),
        migrations.AddField(
            model_name='jump',
            name='id_altitude',
            field=models.ForeignKey(blank=True, db_column='id_altitude', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savejump.altitude'),
        ),
        migrations.AddField(
            model_name='jump',
            name='id_location',
            field=models.ForeignKey(blank=True, db_column='id_location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savejump.location'),
        ),
        migrations.AddField(
            model_name='jump',
            name='id_parachute',
            field=models.ForeignKey(blank=True, db_column='id_parachute', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savejump.parachute'),
        ),
        migrations.AddField(
            model_name='parachute',
            name='aad_dom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='aad_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='aad_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='aad_serial_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='harness_dom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='harness_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='harness_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='harness_serial_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='main_canopy_dom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='main_canopy_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='main_canopy_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='main_canopy_serial_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='main_canopy_size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='reserve_canopy_dom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='reserve_canopy_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='reserve_canopy_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='reserve_canopy_serial_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parachute',
            name='reserve_canopy_size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jump',
            name='id_aircraft',
            field=models.ForeignKey(blank=True, db_column='id_aircraft', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savejump.aircraft'),
        ),
        migrations.AddField(
            model_name='jump',
            name='id_jump_type',
            field=models.ForeignKey(blank=True, db_column='id_jump_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='savejump.jumptype'),
        ),
    ]
