# Generated by Django 5.1.4 on 2024-12-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savejump', '0004_aircraft_jumptype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jump',
            old_name='date',
            new_name='jump_date',
        ),
        migrations.RemoveField(
            model_name='jump',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jump',
            name='parachute',
        ),
    ]
