# Generated by Django 5.1.4 on 2024-12-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savejump', '0005_rename_date_jump_jump_date_remove_jump_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='location_name',
        ),
    ]
